// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "web.herbalbones.com/ui/components"

func Contact() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = components.Layout(contactContent()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func contactContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\r\n        body {\r\n            margin: 0;\r\n        }\r\n        section {\r\n            height: 100vh;\r\n            width: 100%;\r\n            background-color: #060606;\r\n        }\r\n        section img {\r\n            width: 100%;\r\n            aspect-ratio: 0.562;\r\n            object-fit: cover;\r\n        }\r\n\r\n        @media only screen and (min-width: 500px) {\r\n            section {\r\n                position: relative;\r\n            }\r\n            section .blend {\r\n                position: absolute;\r\n                left: 0;\r\n                top: 0;\r\n                bottom: 0;\r\n                right: 0;\r\n                // background: linear-gradient(105deg, rgba(0,0,0,0) 450px, red 800px, blue);\r\n                background: linear-gradient(95deg, rgba(0,0,0,0) 400px, rgba(6,6,6,0.99) 650px, rgba(6,6,6,1)),\r\n                            linear-gradient(155deg, rgba(0,0,0,0) 900px, rgba(6,6,6,1) 1100px, rgba(6,6,6,1));\r\n            }\r\n\r\n            @media only screen and (min-width: 624px) {\r\n                section img {\r\n                    width: 624px;\r\n                    height: auto;\r\n                }\r\n            }\r\n\r\n            @media only screen and (max-height: calc(624px / calc(9 / 16))) {\r\n                section {\r\n                    height: auto;\r\n                }\r\n            }\r\n        }\r\n\r\n    </style><section><img src=\"/static/images/contact-background.jpg\" alt=\"girl wearing blue necklace and earrings\"><div class=\"blend\"></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
